# Generated by Django 5.2.14 on 2026-06-02 06:43

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def backfill_password_hash(apps, schema_editor):
    UserProfile = apps.get_model("quiz", "UserProfile")
    for profile in UserProfile.objects.all():
        if not profile.password_hash:
            profile.password_hash = make_password(profile.student_no)
            profile.save(update_fields=["password_hash"])


def reverse_backfill_password_hash(apps, schema_editor):
    UserProfile = apps.get_model("quiz", "UserProfile")
    UserProfile.objects.filter(password_hash__isnull=False).update(password_hash="")


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.RunPython(backfill_password_hash, reverse_backfill_password_hash),
    ]
