# Generated by Django 5.2.14 on 2026-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_userprofile_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
