# Generated by Django 5.2.14 on 2026-06-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_userprofile_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='start_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
